export const identity = i => i;
export const LEFT = 0;
export const RIGHT = 1;
export const oppDir = dir => (dir === RIGHT ? LEFT : RIGHT);
export const BLACK = "black";
export const RED = "red";
export const CANVAS_WIDTH = 800;
export const CANVAS_HEIGHT = 400;
export const CIRCLE_RADIUS = 20;
export const LINK_DELTA = 3;
export const TRANSITION_DURATION = 2000;
